SELECT C.NAME || ' ' || C.LASTNAME AS 'CLIENTE',
       COUNT(L.CUSTOMER_ID) AS 'LOCAÇÕES'
       FROM CUSTOMERS AS C
       JOIN LOCATIONS AS L ON (L.CUSTOMER_ID = C.ID)

       GROUP BY L.CUSTOMER_ID
       HAVING COUNT(L.CUSTOMER_ID) >= 2;