SELECT C.NAME || ' ' || C.LASTNAME AS 'CUSTOMER',
       COUNT(L.CUSTOMER_ID) AS 'LOCATIONS'
       FROM CUSTOMERS AS C
       JOIN LOCATIONS AS L ON (L.CUSTOMER_ID = C.ID)

       GROUP BY L.CUSTOMER_ID
       HAVING COUNT(L.CUSTOMER_ID) >= 2;